# Assignment 2: NumPy
- **you will learn:** how to create and manipulate NumPy arrays, perform vectorized computations, and use basic NumPy functions for data analysis
- **task:**  See section 2.9 below
- **deadline:** 20.10.2025
- [NumPy documentation](https://numpy.org/doc/stable/)
- 📝 **Reminder:** Sync your GitHub repository with the main course repository, update your project in PyCharm, and after completing the assignment, commit and push your changes back to GitHub.
---

## 2.0 PEP 8 and Code Commenting

### What is PEP 8?
**PEP 8** is the official **style guide** for Python code.
It defines conventions that make your code **clean, consistent, and easy to read**.
While not mandatory, following PEP 8 is considered a sign of **professional and readable coding**.

### Some Important PEP 8 Rules
- ✅ **Line length:** keep lines **under 79 characters**.
- ✅ **Spacing:**
  - add spaces around operators (`a + b`, not `a+b`)
  - add a space **after** commas, not before (`[1, 2, 3]`, not `[1 ,2 ,3]`)
- ✅ **Variable and function names:** use lowercase with underscores (`calculate_mean`, not `CalculateMean`).
- ✅ **Class names:** use `CamelCase` (`DataProcessor`).
- ✅ **Imports:** at the top of the file, one per line.
- ✅ **Blank lines:** use two blank lines between functions.

 **Official guide:** [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

### Comments and Docstrings
Comments explain **what** your code does and **why**.
Every function should include a **docstring** — a text enclosed in triple quotes `""" ... """` that briefly describes the function’s purpose, parameters, and return value.

#### Example:

```python
def calculate_mean(values):
    """
    Compute the arithmetic mean of a list of numbers.

    Parameters
    ----------
    values : list of float
        Input numbers.

    Returns
    -------
    float
        The arithmetic mean of the input values.
    """
    if not values:
        return 0.0
    return sum(values) / len(values)



---
## 2.1 What is a NumPy Array?

- In computer programming, an **array** is a structure for storing and retrieving data.
- They are the foundation for **data science, machine learning, and scientific computing** in Python.
- We often visualize an array as a **grid in space**, with each cell storing one element of data.
- Arrays can be **1D (vectors), 2D (matrices), or higher-dimensional (tensors)**.

Most NumPy arrays have some rules:

1. **Homogeneous type:** All elements must be of the same data type.
2. **Fixed size:** Once created, the total size cannot change.
3. **Rectangular shape:** All rows (in 2D arrays) must have the same number of columns — no jagged arrays.

When these conditions are met, NumPy can exploit them to make arrays:

- **Faster** (optimized C loops under the hood)
- **More memory efficient** (contiguous memory storage)
- **More convenient to use** (vectorized operations without explicit loops)

In [1]:
import numpy as np
from scipy.stats import quantile
import numpy as np
print(np.__version__)

2.3.3


In [2]:
# Create 1D array (vector)
vector = np.array([10, 20, 30, 40, 50])
print("1D array (vector):", vector)
print("Shape:", vector.shape, "Dtype:", vector.dtype)

# Create 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D array (matrix):\n", matrix)
print("Shape:", matrix.shape, "Dtype:", matrix.dtype)

# Vectorized operation: multiply all elements by 2 or square them
matrix2 = 2 * matrix
matrix_sq = matrix ** 2
print("Matrix after multiplying by 2:\n", matrix2)
print("Matrix after squaring by 2:\n", matrix_sq)

1D array (vector): [10 20 30 40 50]
Shape: (5,) Dtype: int64
2D array (matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3) Dtype: int64
Matrix after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix after squaring by 2:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


---
## 2.2 Constructing arrays

There are several mechanisms for creating arrays. Among others:

1. **Conversion from other Python structures**
   Arrays can be created directly from existing **lists or tuples** using `np.array()`.
   This is the most common and straightforward way to build an array from existing data.

In [ ]:
# Conversion from Python structures
a = np.array([1, 2, 3, 4, 5])
b= np.array(((1,0),(0,1)))
c = np.array([([1,2],[2,1]), ([3,1],[1,3])])
print("From list:\n", a)
print("From tuples of tuples:\n", b)
print("From list of tuples or lists:\n", c)


2. **NumPy array creation functions**
   NumPy provides a set of **built-in constructors** such as `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`
   to generate arrays of a specific shape or with evenly spaced values.

In [ ]:
# np.empty(shape, dtype)
# Creates a new array *without initializing* its entries (values are arbitrary).
arr_empty = np.empty((2,3), dtype="int32")
print("np.empty:\n", arr_empty)
print("np.empty type:", arr_empty.dtype)

In [ ]:
# np.identity(n)
# Shortcut for creating a square identity matrix (ones on the main diagonal).
arr_identity = np.identity(4)
print("np.identity:\n", arr_identity)

In [ ]:
# np.eye(N, M, k)
# Creates a 2D array with ones on the main (or k-th) diagonal, zeros elsewhere.
arr_eye = np.eye(4,4,-1)
print("np.eye:\n", arr_eye)

In [ ]:
# np.ones(shape, dtype)
# Creates an array of given shape filled with ones.
arr_ones = np.ones((2, 4))
print("np.ones:\n", arr_ones)

In [ ]:
# np.zeros(shape, dtype)
# Creates an array filled with zeros.
arr_zeros = np.zeros((3, 3))
print("np.zeros:\n", arr_zeros)

In [ ]:
# np.full(shape, fill_value)
# Creates an array filled with a specified constant value.
arr_full = np.full((2, 3), fill_value=7)
print("np.full:\n", arr_full)

In [ ]:
# np.empty_like(prototype)
# Creates an uninitialized array with the *same shape and dtype* as another array.
prototype = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
arr_zeros_like = np.zeros_like(prototype)
print("np.empty_like:\n", arr_zeros_like)

# Similarly with np.empty_like(a), np.zeros_like(a), np.full_like(a, fill_value)

In [ ]:
# np.arange([start,] stop[, step,][, dtype])
# Returns evenly spaced values within a given interval.
# Similar to Python's range(), but returns a NumPy array.
arr_arange = np.arange(0, 10, 2, dtype=float)
print("np.arange:\n", arr_arange)

In [ ]:
# np.linspace(start, stop[, num, endpoint])
# Returns evenly spaced numbers over a specified interval.
# Unlike arange, it lets you specify the number of samples.
arr_linspace = np.linspace(0, 1, num=5)
print("np.linspace:\n", arr_linspace)

In [ ]:
# np.diag(v[, k])
# Construct a diagonal matrix from a 1D array, or extract a diagonal from a 2D array.
v = np.array([1, 2, 3])
arr_diag = np.diag(v)
print("np.diag (construct from 1D):\n", arr_diag)

In [ ]:
# np.tril(m[, k])
# Return the lower triangle of an array (elements above the k-th diagonal are zeroed).
m = np.arange(1, 10).reshape(3, 3)
arr_tril = np.tril(m)
print("np.tril (lower triangle):\n", arr_tril)

# similarly with np.triu(m[, k])


3. **Replicating, joining, or mutating existing arrays**
   Arrays can be **copied, concatenated, reshaped, or repeated** to create new ones.
   For example, you can use `np.tile`, `np.concatenate`, or `reshape` for this purpose.

In [ ]:
# np.reshape(a, newshape)
# Changes the shape of an array without changing its data.
a = np.arange(6)
print("a:\n", a)
reshaped = np.reshape(a, (3, 2))
print("np.reshape:\n", reshaped)

In [ ]:
# a.flatten()
# Flatten a multi-dimensional array into 1D.
a2 = np.array([[1, 2], [3, 4]])
print("a.flatten:\n", a2.flatten())

In [ ]:
# np.transpose(a) or a.T
# Swaps axes, e.g., turns rows into columns.
print("np.transpose:\n", np.transpose(a2))

In [ ]:
# np.swapaxes(a, axis1, axis2)
# Swaps any two axes in a multi-dimensional array.
a3 = np.arange(8).reshape(2, 2, 2)
print("a3:\n", a3)
print("np.swapaxes:\n", np.swapaxes(a3, 0, 2))

In [ ]:
# np.moveaxis(a, source, destination)
# Moves a given axis to a new position.
a4 = np.zeros((2, 3, 4))
print("np.moveaxis shape:", np.moveaxis(a4, 0, -1).shape)

In [ ]:
# np.squeeze(a)
# Removes axes of length 1.
a5 = np.zeros((1, 3, 1))
print("a5:\n", a5)
print("np.squeeze shape:", np.squeeze(a5).shape)
print("a5 squeezed:\n", np.squeeze(a5))

In [ ]:
# np.expand_dims(a, axis)
# Adds a new dimension (axis) to the array.
a6 = np.array([1, 2, 3])
print("np.expand_dims shape:", np.expand_dims(a6, axis=0).shape)

In [ ]:
# np.concatenate((a1, a2, ...), axis)
# Joins arrays along an existing axis.
a7 = np.ones((2, 2))
b7 = np.zeros((2, 2))
print("np.concatenate:\n", np.concatenate((a7, b7), axis=1))

In [ ]:
# np.stack((a1, a2, ...), axis)
# Stacks arrays along a new axis.
a8 = np.array([1, 2])
b8 = np.array([3, 4])
print("np.stack:\n", np.stack((a8, b8), axis=0))

In [ ]:
# np.split(a, sections, axis)
# Splits an array into multiple subarrays.
x = np.arange(9)
print("np.split:\n", np.split(x, 3))

In [ ]:
# np.copy(a)
# Creates a deep copy of the array (independent of the original).
a11 = np.array([1, 2, 3])
b11 = a11.copy()
b11[0] = 99
print("Original:", a11, " | Copy:", b11)

In [ ]:
# np.astype(dtype)
# Converts array elements to a new type.
a12 = np.array([1, 2, 3])
print("astype to float:\n", a12.astype(float))

In [ ]:
# np.clip(a, min, max)
# Limits values to a given range.
a13 = np.array([-1, 0, 2, 5])
print("np.clip:\n", np.clip(a13, 0, 3))

In [ ]:
# np.where(condition, x, y)
# Selects elements based on a condition.
a14 = np.array([1, 2, 3])
print("np.where (a > 1 -> 100):\n", np.where(a14 > 1, 100, a14))


4. **Creating Arrays from Other Libraries**

Many Python libraries — such as **SciPy**, **Pandas**, and **OpenCV** — use NumPy `ndarray` objects as a **common format for data exchange**.
These libraries can **create**, **manipulate**, and **interoperate with** NumPy arrays directly.


---
## 2.3 Indexing arrays

Note that Python indexes (unlike for example R) start from 0, not from 1.

### Basic Indexing

In [ ]:
# Create a 2D array for demonstration
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Single element indexing
print("Single element x[1, 2]:", x[1, 2])
print("Same by chained indexing x[1][2]:", x[1][2])

In [ ]:
# 2. If fewer indices than dimensions, returns a subarray (view)
print("x[0] returns first row (view):", x[0])

In [ ]:
# 3. Slicing (rows, columns)
print("x[0:2, 1:4] → rows 0 and 1, columns 1 to 3:\n", x[0:2, 1:4])

In [ ]:
# 4. Striding with step (convention start:stop:step)
print("x[:, ::2] → all rows, every second column:\n", x[:, ::2])

In [ ]:
# 5. Using negative indices
print("x[-1, -2]:", x[-1, -2])  # last row, second-last column

In [ ]:
# 6. Ellipsis (`...`) and `newaxis` (alias None)
# Ellipsis expands to as many ":" as needed
print("x[..., 2] → same as x[:, 2]:", x[..., 2])

# newaxis introduces a new dimension
y = x[:, 1]  # shape (3,)
y2 = x[:, 1, np.newaxis]  # shape (3,1)
print("y shape:", y.shape, "   y2 shape:", y2.shape)

- All slicing operations produce views, not copies — they refer to the same underlying data.
- Because of this, modifying a slice will affect the original array.
- When using integer indexing (not slicing), you reduce a dimension.
- : means “select all elements along this axis”.
- ... is a convenient placeholder to fill in missing : for remaining axes.

### Advanced Indexing

In [ ]:
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Integer array indexing
row_idx = [0, 2]
col_idx = [1, 3]
# Select elements (0,1) and (2,3)
print("x[row_idx, col_idx]:", x[row_idx, col_idx])

# Equivalent as
print("The same as:", np.array([x[0,1],x[2,3]]))

In [ ]:
# 2. Broadcasting integer indices
# If you supply fewer index arrays or scalars, they broadcast
print("x[row_idx, 2]:", x[row_idx, 2])
print("The same as:", x[[0,2], [2,2]])

In [ ]:
# 3. Boolean masking (Boolean indexing)
mask = x % 2 == 0  # True for even numbers
print("Boolean mask:\n", mask)
print("x[mask] → all even elements:", x[mask])

# Example modification using Boolean mask
x2 = x.copy()
x2[x2 % 2 == 1] = -1
print("x2 with odd elements replaced by –1:\n", x2)

In [ ]:
# 4. Combining basic and advanced indexing
# e.g. select rows 0 and 2, but columns 1:3
print("x[[0, 2], 1:3]:\n", x[[0, 2], 1:3])

---
## 2.4 Array attributes

- Every NumPy array is a Python object of class `numpy.ndarray`.
- Besides storing the actual data, it also stores various attributes that describe its structure and memory layout.

In [ ]:
# Let's create a simple 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Type of numpy array object:", type(a))

In [ ]:
print("Number of dimensions (ndim):", a.ndim)
print("Shape (rows, columns):", a.shape)
print("Total number of elements (size):", a.size)
print("Data type (dtype):", a.dtype)
print("Size of one element in bytes (itemsize):", a.itemsize)
print("Total size in bytes (nbytes):", a.nbytes)
print("Transposed array (T):\n", a.T)

Example explanation:
- ndim   → tells how many axes (dimensions) the array has
- shape  → gives the length of each dimension as a tuple
- size   → total count of elements = product of shape entries
- dtype  → data type of the elements (e.g. int32, float64)
- itemsize → bytes per element, depends on dtype
- nbytes   → total memory used by the array
- T        → shorthand for the transposed view (rows <-> columns)


---
## 2.5 Array methods

- A NumPy ndarray provides many built-in methods that operate on the array or return information about it. Most of these methods return a new array or a computed value derived from the data.

In [ ]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the array to 3 rows and 2 columns
reshaped = a.reshape(3, 2)
print("Reshaped array:\n", reshaped)

# Flatten the array to 1D
flattened = a.flatten()
print("\nFlattened array:", flattened)

In [ ]:
# --- Max and Min ---
print("Max element:", a.max())                  # ndarray.max()
print("Index of max (flattened):", a.argmax())  # ndarray.argmax()
print("Min element:", a.min())                  # ndarray.min()
print("Index of min (flattened):", a.argmin())  # ndarray.argmin()

In [ ]:
# --- Rounding ---
arr_float = np.array([[1.234, 2.567], [3.891, 4.456]])
rounded = arr_float.round(1)             # Round to 1 decimal
print("Rounded array:\n", rounded)

In [ ]:
# --- Trace ---
print("Trace (sum of diagonal):", a.trace())  # Sum along main diagonal

In [ ]:
# --- Sum, Cumsum, Mean ---
print("Sum of all elements:", a.sum())
print("Cumulative sum along rows:\n", a.cumsum(axis=1))
print("Mean along columns:", a.mean(axis=0))

In [ ]:
# --- Variance and Standard Deviation ---
print("Variance of all elements:", a.var())
print("Standard deviation:", a.std())

In [ ]:
# --- Logical checks ---
print("All elements > 0?", (a > 0).all())
print("Any element > 5?", (a > 5).any())

---
## 2.6 Arithmetic and linear algebra


In [ ]:
# Create example arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Array a:\n", a)
print("Array b:\n", b)


In [ ]:
# Addition (elementwise)
print("Addition (a + b):\n", a + b)

# Subtraction (elementwise)
print("Subtraction (a - b):\n", a - b)

# Multiplication (elementwise)
print("Elementwise multiplication (a * b):\n", a * b)

# Division (elementwise)
print("Elementwise division (a / b):\n", a / b)

# Exponentiation (elementwise)
print("Elementwise power (a ** 2):\n", a ** 2)

# Modulo (elementwise)
print("Elementwise modulo (b % a):\n", b % a)

In [ ]:
# Matrix multiplication
matmul = a @ b  # or np.matmul(a, b)
print("Matrix multiplication (a @ b):\n", matmul)

# Dot product
dot = np.dot(a[0], b[0])
print("Dot product (np.dot(a[0], b[0])):\n", dot)

# Transpose
print("Transpose of a (a.T):\n", a.T)

# Determinant
det = np.linalg.det(a)
print("Determinant of a:", det)

# Inverse
inv = np.linalg.inv(a)
print("Inverse of a:\n", inv)

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(a)
print("Eigenvalues of a:", eigvals)
print("Eigenvectors of a:\n", eigvecs)

# Norms
norm_a0 = np.linalg.norm(a[0])
print("Frobenius norm of a[0]:", norm_a0)

---
## 2.7 Miscellaneous

**NumPy** provides optimized **mathematical functions** that work directly on entire arrays (`np.array` objects). These functions are implemented in **compiled C code**, which makes them **very fast**. They automatically apply the operation **elementwise** to all elements in the array — this is called **vectorization**.

In [ ]:
# These are elementwise functions that operate efficiently on ndarrays.

# Create an example array
a = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Array a:\n", a)

# Elementwise trigonometric functions
print("sin(a):", np.sin(a))

In [ ]:
b = np.array([1, 2, 3, 4])
print("Array b:\n", b)

# Exponential
print("Exponential (e^b):", np.exp(b))

# Logarithms
print("Natural log (ln(b)):", np.log(b))
print("Log base 10:", np.log10(b))

# Power
print("b cubed:", np.power(b, 3))
c = np.array([1.234, 5.678, -9.1011])

# Round to nearest integer
print("Rounded:", np.round(c))

# Floor and ceiling
print("Floor:", np.floor(c))
print("Ceil:", np.ceil(c))

# Absolute values
print("Absolute values:", np.abs(c))
d = np.array([1, 2, 3, 4, 5])

# Sum/product
print("Sum:", np.sum(d))
print("Product:", np.prod(d))

---
## 2.8 Python lists vs NumPy arrays

Python lists are flexible but **slow and memory-inefficient** for numerical computations.
NumPy arrays (`ndarray`) store data in **contiguous memory** and support **vectorized operations**, making them much faster and smaller in memory footprint.

Let's compare both in terms of **execution speed** and **memory usage**.

In [ ]:
import time, sys

# Create a large list and a NumPy array
n = 1_000_000
py_list = list(range(n))
np_array = np.arange(n)

# Compare memory usage of both objects
list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
array_mem = np_array.nbytes
print(f"Python list memory: {list_mem / 1e6:.2f} MB")
print(f"NumPy array memory: {array_mem / 1e6:.2f} MB")
print(f"Memory ratio (list / array): {list_mem / array_mem:.1f}×")

# Compute 2x Python list
list_start = time.time()
list_result = [x * 2 for x in py_list]
list_end = time.time()
print(f"Python list time: {list_end - list_start:.5f} s")

# Compute 2x NumPy array
array_start = time.time()
array_result = np_array * 2
array_end = time.time()
print(f"NumPy array time: {array_end - array_start:.5f} s")
print(f"Execution speed ratio (list / array): {(list_end - list_start) / (array_end - array_start):.1f}×")

**Observation:**

- NumPy operations are much faster because they run in optimized C loops rather than Python loops.
- NumPy arrays use far less memory because all elements share the same data type and they are stored in an efficient way

➡️ This demonstrates the two biggest advantages of NumPy:
1. **Vectorization** (no explicit loops)
2. **Efficient memory representation**

---
## 2.9  🏠 Homework: NumPy Arrays in Data Science

### Task Overview
In this assignment, you will practice working with **NumPy arrays** and **mathematical functions** to perform a mini data analysis. You will simulate a small part of a **data preprocessing pipeline** — a common step in data science when dealing with multivariate datasets.

### Your Task

1. **Generate synthetic data:**
   - Create a NumPy array `data` of shape **(100, 10)** — representing 100 samples and 10 features.
   - The values should be drawn from a **normal distribution** with mean = 50 and standard deviation = 10 using
      `np.random.normal(loc=50, scale=10, size=(100, 10))`.
   - Print the shape, data type, and the **first 5 rows** of the array.

2. **Data cleaning:**
   - Replace all values **smaller than 20** or **larger than 80** with `np.nan` (treat them as outliers).
   - Print how many `np.nan` values are now in the array.

3. **Handle missing values:**
   - Compute the **mean of each column** ignoring missing values (`np.nanmean`).
   - Replace all `np.nan` values in each column with that column’s mean.

4. **Data transformation:**
   - **Standardize each column** so that it has mean 0 and standard deviation 1.
   - Create a new array where:
     - all positive standardized values are replaced with their **square roots**,
     - negative values remain unchanged.
   - For the first 5 rows, also compute the **exponential (`np.exp`)** of all standardized values and print the result.

5. **Array indexing and logical operations:**
   - Compute the **75th percentile** for each column.
   - Create a Boolean mask that marks all values above the 75th percentile.
   - Print how many such “high” values there are in total.
   - Replace all values **below the 25th percentile** (computed column-wise) with the 25th percentile value (a simple form of *winsorization*).

6. **Descriptive statistics:**
   - Compute and print for the final cleaned dataset:
     - column-wise **mean**, **median**, **variance**, and **standard deviation**,
     - the **overall mean** of the entire array,
     - and the **minimum and maximum** values per column.

### ✍️ Hints
- Use functions such as `np.mean`, `np.std`, `np.nanmean`, `np.isnan`, `np.where`, `np.percentile`, `np.sqrt`, and `np.exp`.
- Remember to specify the `axis` argument when computing column-wise statistics (`axis=0`).
- Use **vectorized operations** — avoid `for` loops.
- Include **comments or docstrings** to make your code clear and readable.


---
## Your solution:


In [73]:
## 1
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Richard\\PycharmProjects\\python-for-data-science\\.venv\\Lib\\site-packages\\numpy\\version.py'>


In [77]:
my_vector = np.random.normal(loc=50, scale=10, size=(100, 10)) ## creating 2D array, dim = 100x10
print(my_vector.min(), my_vector.max()) ## print its min and max
print(my_vector.shape, my_vector.dtype) ## array's shape and data type
print(my_vector[0:5]) ## print first 5 rows

12.606831069657034 86.42253072112673
(100, 10) float64
[[68.31159567 56.71112966 71.36157279 59.39997236 54.35955695 59.30887343
  52.62528134 44.81139895 40.89289851 61.72328638]
 [67.426189   61.08658053 57.63800125 45.7234212  41.46213362 62.88127611
  54.75631986 67.47070786 46.8018752  40.89128601]
 [51.2522388  49.02752531 48.01734236 41.27822578 56.80819997 39.78877489
  47.58944006 55.01988453 67.10712499 48.92564211]
 [32.87406263 59.10990082 54.33738852 37.66770611 35.87080459 48.90325842
  56.014204   37.63211772 43.46203698 54.91716368]
 [66.09510015 48.76111528 34.52631811 49.69722515 47.44320188 48.33171092
  57.98251282 49.8727676  61.21551405 48.88702187]]


In [ ]:
## 2

In [78]:
my_vector_copy = my_vector.copy()
my_vector_copy = my_vector_copy.astype(float) ## turning the array into float so it is easier to work with the mask
mask =(my_vector_copy > 80) | (my_vector_copy < 20)
my_vector_copy[mask] = np.nan ## the elements that match the mask are assigned 'nan'
print(my_vector_copy)
count_nan = np.isnan(my_vector_copy).sum() ## how many nan elements are there
print("Number of NaN values:", count_nan) ## print above

[[68.31159567 56.71112966 71.36157279 59.39997236 54.35955695 59.30887343
  52.62528134 44.81139895 40.89289851 61.72328638]
 [67.426189   61.08658053 57.63800125 45.7234212  41.46213362 62.88127611
  54.75631986 67.47070786 46.8018752  40.89128601]
 [51.2522388  49.02752531 48.01734236 41.27822578 56.80819997 39.78877489
  47.58944006 55.01988453 67.10712499 48.92564211]
 [32.87406263 59.10990082 54.33738852 37.66770611 35.87080459 48.90325842
  56.014204   37.63211772 43.46203698 54.91716368]
 [66.09510015 48.76111528 34.52631811 49.69722515 47.44320188 48.33171092
  57.98251282 49.8727676  61.21551405 48.88702187]
 [60.42373581 57.79822958 44.62318418 50.08446203 54.50759032 51.70941165
          nan 61.33850725 51.00191696 61.92586332]
 [52.04074955 47.33085761 52.00928011 55.20229542 47.13700906 51.27617246
  49.97517548 45.00866747 67.94892043 50.29480901]
 [58.4520109  41.13550496 48.80552976 49.77148292 47.03250321 55.45259919
  48.5300924  48.95213048 42.96022049 54.10380661]


In [79]:
means = np.nanmean(my_vector_copy, axis=0) ## calculating means of columns (axis = 0 ... colmuns, axis = 1 ... rows)
print(means)

[51.09012371 50.00316607 49.7870685  48.81776906 50.32029131 49.93725066
 51.46486286 49.28170017 51.12689775 49.03400512]


In [80]:
inds = np.where(np.isnan(my_vector_copy)) ## identifying the location of nan elements
print(inds)
my_vector_copy[inds] = np.take(means, inds[1]) ## replacing nan with means
print(my_vector_copy)

[[68.31159567 56.71112966 71.36157279 59.39997236 54.35955695 59.30887343
  52.62528134 44.81139895 40.89289851 61.72328638]
 [67.426189   61.08658053 57.63800125 45.7234212  41.46213362 62.88127611
  54.75631986 67.47070786 46.8018752  40.89128601]
 [51.2522388  49.02752531 48.01734236 41.27822578 56.80819997 39.78877489
  47.58944006 55.01988453 67.10712499 48.92564211]
 [32.87406263 59.10990082 54.33738852 37.66770611 35.87080459 48.90325842
  56.014204   37.63211772 43.46203698 54.91716368]
 [66.09510015 48.76111528 34.52631811 49.69722515 47.44320188 48.33171092
  57.98251282 49.8727676  61.21551405 48.88702187]
 [60.42373581 57.79822958 44.62318418 50.08446203 54.50759032 51.70941165
  51.46486286 61.33850725 51.00191696 61.92586332]
 [52.04074955 47.33085761 52.00928011 55.20229542 47.13700906 51.27617246
  49.97517548 45.00866747 67.94892043 50.29480901]
 [58.4520109  41.13550496 48.80552976 49.77148292 47.03250321 55.45259919
  48.5300924  48.95213048 42.96022049 54.10380661]


In [ ]:
## 4

In [81]:
my_vector_normed = (my_vector_copy-means)/np.std(my_vector_copy, axis=0)
print(my_vector_normed)

[[ 1.86937907e+00  6.97389978e-01  2.16208162e+00  1.03266028e+00
   4.00892755e-01  1.04423893e+00  1.21219148e-01 -4.65925259e-01
  -1.02103996e+00  1.14851921e+00]
 [ 1.77326878e+00  1.15228147e+00  7.86778560e-01 -3.01960758e-01
  -8.79162589e-01  1.44229614e+00  3.43830798e-01  1.89578235e+00
  -4.31504904e-01 -7.37005440e-01]
 [ 1.75974835e-02 -1.01431989e-01 -1.77352504e-01 -7.35743461e-01
   6.43917932e-01 -1.13080026e+00 -4.04832789e-01  5.98072682e-01
   1.59433768e+00 -9.80804188e-03]
 [-1.97734104e+00  9.46776985e-01  4.56008776e-01 -1.08807465e+00
  -1.43409596e+00 -1.15213232e-01  4.75231362e-01 -1.21419888e+00
  -7.64718559e-01  5.32490414e-01]
 [ 1.62877999e+00 -1.29129170e-01 -1.52935092e+00  8.58213877e-02
  -2.85548020e-01 -1.78898270e-01  6.80844012e-01  6.16050761e-02
   1.00653519e+00 -1.33035971e-02]
 [ 1.01315725e+00  8.10409761e-01 -5.17496914e-01  1.23609751e-01
   4.15584907e-01  1.97464148e-01  0.00000000e+00  1.25664260e+00
  -1.24692579e-02  1.16685465e+00

In [82]:
mask2 = my_vector_normed>0
my_vector_normed[mask2] = np.sqrt(my_vector_normed[mask2])
print(my_vector_normed)
first5 = my_vector_normed[0:5]
exp = np.exp(first5)

[[ 1.36725238e+00  8.35098783e-01  1.47040186e+00  1.01619894e+00
   6.33160924e-01  1.02188010e+00  3.48165403e-01 -4.65925259e-01
  -1.02103996e+00  1.07168989e+00]
 [ 1.33164138e+00  1.07344374e+00  8.87005389e-01 -3.01960758e-01
  -8.79162589e-01  1.20095634e+00  5.86370870e-01  1.37687412e+00
  -4.31504904e-01 -7.37005440e-01]
 [ 1.32655507e-01 -1.01431989e-01 -1.77352504e-01 -7.35743461e-01
   8.02444971e-01 -1.13080026e+00 -4.04832789e-01  7.73351590e-01
   1.26267085e+00 -9.80804188e-03]
 [-1.97734104e+00  9.73024658e-01  6.75284219e-01 -1.08807465e+00
  -1.43409596e+00 -1.15213232e-01  6.89370265e-01 -1.21419888e+00
  -7.64718559e-01  7.29719408e-01]
 [ 1.27623665e+00 -1.29129170e-01 -1.52935092e+00  2.92952876e-01
  -2.85548020e-01 -1.78898270e-01  8.25132724e-01  2.48203699e-01
   1.00326228e+00 -1.33035971e-02]
 [ 1.00655712e+00  9.00227616e-01 -5.17496914e-01  3.51581784e-01
   6.44658752e-01  4.44369382e-01  0.00000000e+00  1.12100072e+00
  -1.24692579e-02  1.08021046e+00

In [83]:
print(exp)

[[3.92455269 2.30504174 4.35098327 2.76267368 1.88355495 2.77841354
  1.41646652 0.62755419 0.36022013 2.92031032]
 [3.78725463 2.92543663 2.42784829 0.73936708 0.4151304  3.32329361
  1.79745337 3.96249597 0.64953088 0.4785448 ]
 [1.14185657 0.90354263 0.83748452 0.4791491  2.23098897 0.32277485
  0.66708835 2.16701705 3.53484995 0.9902399 ]
 [0.13843685 2.64593542 1.96459127 0.33686445 0.23833073 0.8911761
  1.99246042 0.29694781 0.46546491 2.07449844]
 [3.58312975 0.87886044 0.21667626 1.34037963 0.75160225 0.83619096
  2.28218364 1.28172099 2.72716409 0.9867845 ]]


In [ ]:
## 5

In [85]:
upper_kvantil = np.quantile(my_vector_normed, 0.75, axis = 0)
print(upper_kvantil)
mask3 = my_vector_normed > upper_kvantil
count_nad = (my_vector_normed> upper_kvantil).sum()
print(count_nad)

[0.81115038 0.86757618 0.82624721 0.78433527 0.80089624 0.8796165
 0.83927727 0.80874164 0.90009328 0.84968865]
250


In [89]:
# Replace all values **below the 25th percentile** (computed column-wise) with the 25th percentile value (a simple form of *winsorization*).
lower_kvantil = np.quantile(my_vector_normed, 0.25, axis = 0)
print(lower_kvantil)
mask4 = my_vector_normed < lower_kvantil
my_vector_normed = np.where(mask4, lower_kvantil, my_vector_normed)
print(my_vector_normed)

[-0.62855245 -0.63958897 -0.58719241 -0.73584101 -0.63073793 -0.85523245
 -0.67215158 -0.66186057 -0.81818978 -0.58853662]
[[ 1.36725238e+00  8.35098783e-01  1.47040186e+00  1.01619894e+00
   6.33160924e-01  1.02188010e+00  3.48165403e-01 -4.65925259e-01
  -8.18189780e-01  1.07168989e+00]
 [ 1.33164138e+00  1.07344374e+00  8.87005389e-01 -3.01960758e-01
  -6.30737925e-01  1.20095634e+00  5.86370870e-01  1.37687412e+00
  -4.31504904e-01 -5.88536625e-01]
 [ 1.32655507e-01 -1.01431989e-01 -1.77352504e-01 -7.35743461e-01
   8.02444971e-01 -8.55232451e-01 -4.04832789e-01  7.73351590e-01
   1.26267085e+00 -9.80804188e-03]
 [-6.28552453e-01  9.73024658e-01  6.75284219e-01 -7.35841015e-01
  -6.30737925e-01 -1.15213232e-01  6.89370265e-01 -6.61860571e-01
  -7.64718559e-01  7.29719408e-01]
 [ 1.27623665e+00 -1.29129170e-01 -5.87192415e-01  2.92952876e-01
  -2.85548020e-01 -1.78898270e-01  8.25132724e-01  2.48203699e-01
   1.00326228e+00 -1.33035971e-02]
 [ 1.00655712e+00  9.00227616e-01 -5.17496

In [ ]:
## 6

In [90]:
fin_col_mean = np.mean(my_vector_normed, axis = 0)
fin_col_median = np.median(my_vector_normed, axis = 0)
fin_col_var = np.var(my_vector_normed, axis = 0)
fin_col_st = np.sqrt(fin_col_var)
print("The means of each collumn:" , fin_col_mean)
print("The median of each collumn:" , fin_col_median)
print("The variance of each collumn:" , fin_col_var)
print("The standard deviation of each collumn:" , fin_col_st)

The means of each collumn: [0.17134193 0.18068571 0.16783944 0.15177209 0.18648308 0.14785968
 0.154053   0.1468795  0.11538285 0.20523185]
The median of each collumn: [ 0.07370975 -0.01476745 -0.0810632   0.19784621 -0.00316382  0.25963953
 -0.05708817 -0.01319924 -0.00623463  0.27410754]
The variance of each collumn: [0.49353542 0.49001121 0.48723089 0.53400842 0.49082175 0.60503683
 0.51795764 0.54515494 0.65615044 0.47584306]
The standard deviation of each collumn: [0.70252076 0.70000801 0.69801926 0.7307588  0.70058672 0.77784113
 0.71969274 0.73834608 0.81003114 0.68981379]


In [92]:
over_mean = np.mean(my_vector_normed)
print("The mean of the whole thing:" , over_mean)
fin_col_min = np.min(my_vector_normed, axis = 0)
fin_col_max = np.max(my_vector_normed, axis = 0)
print("The minima of each collumn:" , fin_col_min)
print("The maxima of each collumn:" , fin_col_max)

The mean of the whole thing: 0.1627529134697125
The minima of each collumn: [-0.62855245 -0.63958897 -0.58719241 -0.73584101 -0.63073793 -0.85523245
 -0.67215158 -0.66186057 -0.81818978 -0.58853662]
The maxima of each collumn: [1.54260922 1.60570968 1.53508284 1.73097068 1.56076356 1.65709171
 1.63112496 1.62468931 1.52522828 1.36250892]
